repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      # Run the linter
      - id: ruff-check
        args: [ --fix, --show-fixes ]
      # Run the formatter
      - id: ruff-format

  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Apply a file size limit of 500kB
      - id: check-added-large-files
      # Simple parser validation of e.g. pyproject.toml
      - id: check-toml
      # Unify file endings
      - id: end-of-file-fixer

  # GitHub Actions Workflow linter
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
